export const environment = {
    production: false,
    baseUrl: 'http://localhost:8088',
    customer: 'customer',
    registration: 'add',
    authenticate: 'auth',
    login: 'login',
    activation: 'activation',
    company: 'company',
    findAll: 'findAll',
    getById: 'getById',
    storage: 'storage',
    getAvailableByCompany: 'getAvailableByCompany',
    appointment: 'appointment',
    reservation: 'reservation',
    reservationStorage: 'reservationStorage',
    getEquipmentByReservation: 'getEquipmentByReservation',
    getCreatedForCustomer: 'getCreatedForCustomer',
}